const Terms = () => {
    return (
        <p>
            BITE NINJA, INC.

            

            TECHNOLOGY SERVICES AGREEMENT

            Last update: 05/13/2021

            This Technology Services Agreement (“Agreement”) constitutes a legal agreement between you, an  individual (“you”) and BITE NINJA, INC. (as applicable, “Company”).

            Company, (“BITE NINJA”), provides lead generation to independent  providers of Customer Service or B2C (collectively, “P2P”) Customer Service services using the  BITE NINJA Services (as defined below). The BITE NINJA Services enable an authorized Customer provider to  seek, receive and fulfill requests for Customer services from an authorized user of BITE NINJA’s mobile  applications. You desire to enter into this Agreement for the purpose of accessing and using the BITE NINJA  Services.

            You acknowledge and agree that Company is a technology services provider that does not provide  Customer services.

            In order to use the BITE NINJA Services, you must agree to the terms and conditions that are set forth below.   Upon your execution (electronic or otherwise) of this Agreement, you and Company shall be bound by  the terms and conditions set forth herein.

            IMPORTANT: PLEASE NOTE THAT TO USE THE BITE NINJA SERVICES, YOU MUST AGREE  TO THE TERMS AND CONDITIONS SET FORTH BELOW. PLEASE REVIEW THE  ARBITRATION PROVISION SET FORTH BELOW CAREFULLY, AS IT WILL REQUIRE  YOU TO RESOLVE DISPUTES WITH THE COMPANY ON AN INDIVIDUAL BASIS,  EXCEPT AS PROVIDED IN SECTION 15.3, THROUGH FINAL AND BINDING  ARBITRATION UNLESS YOU CHOOSE TO OPT OUT OF THE ARBITRATION  PROVISION.  BY VIRTUE OF YOUR ELECTRONIC EXECUTION OF THIS AGREEMENT,  YOU WILL BE ACKNOWLEDGING THAT YOU HAVE READ AND UNDERSTOOD ALL  OF THE TERMS OF THIS AGREEMENT (INCLUDING THE ARBITRATION PROVISION)  AND HAVE TAKEN TIME TO CONSIDER THE CONSEQUENCES OF THIS IMPORTANT  BUSINESS DECISION.  IF YOU DO NOT WISH TO BE SUBJECT TO ARBITRATION,  YOU MAY OPT OUT OF THE ARBITRATION PROVISION BY FOLLOWING THE  INSTRUCTIONS PROVIDED IN THE ARBITRATION PROVISION BELOW.

            1. Definitions

            1.1 “Affiliate” means an entity that, directly or indirectly, controls, is under the control of, or is  under common control with a party, where control means having more than fifty percent (50%)  of the voting stock or other ownership interest or the majority of the voting rights of such entity.

            1.2 “City Addendum” means an addendum or supplemental information to this Agreement setting  forth additional Account-specific terms, as made available and as updated by Company from  time to time.

            1.3 “Company Data” means all data related to the access and use of the BITE NINJA Services hereunder,  including all data related to Users (including User Information), all data related to the provision  of Customer Services via the BITE NINJA Services and the Ninja App, and the Ninja ID.

            1.4 “Company Device” means a mobile device owned or controlled by Company that is provided to  you solely for your use of the Ninja App to provide Customer Services.

            1.5 “Device” means a Company Device or Your Device, as the case may be.

            1.6 “Ninja App” means the mobile application provided by Company that enables Customer  providers to access the BITE NINJA Services for the purpose of seeking, receiving and fulfilling on demand requests for Customer services by Users, as may be updated or modified from time  to time.

            1.7 “Ninja ID” means the identification and password key assigned by Company to you that enables  you to use and access the Ninja App.

            1.8 “Fee” has the meaning set forth in Section 4.1.

            1.9 “Service Fee” has the meaning set forth in Section 4.4.

            1.10 “Account” means the city or metro areas in the United States in which you are enabled by the  Ninja App to receive requests for Customer Services.

            1.11 “Access Points” means any applicable access point to additional networks and software.

            1.12 “Customer Services” means your provision of P2P Customer Service services to  Users via the BITE NINJA Services in the Account using the Computer.

            1.13 “BITE NINJA Services” mean BITE NINJA’s on-demand lead generation and related services licensed by BITE NINJA  to Company that enable Customer providers to seek, receive and fulfill on-demand  requests for Customer services by Users seeking Customer services; such BITE NINJA Services  include access to the Ninja App and BITE NINJA’s software, websites, payment services as described  in Section 4 below, and related support services systems, as may be updated or modified from  time to time.

            1.14 “User” means an end user authorized by BITE NINJA to use the BITE NINJA mobile application for the  purpose of obtaining Customer Services offered by Company’s Customer provider  customers.

            1.15 “User Information” means information about a User made available to you in connection with  such User’s request for and use of Customer Services, which may include the User’s name,  Access location, contact information and photo.

            1.16 “Computer” means your Computer that:  (a) meets the then-current Company requirements for a Computer on the BITE NINJA Services; and (b) Company authorizes for your use for the purpose of  providing Customer Services.

            1.17 “Your Device” means a mobile device owned or controlled by you:  (a) that meets the then current Company specifications for mobile devices as set forth at www.biteninja.com/byod;  and (b) on which the Ninja App has been installed as authorized by Company solely for the  purpose of providing Customer Services.

            2. Use of the BITE NINJA Services

            2.1 Ninja IDs. BITE NINJA will issue you a Ninja ID to enable you to access and use the Ninja App on a  Device in accordance with this Agreement. Company reserves the right to deactivate your Ninja  ID if you have not fulfilled a request for Customer Services using the Ninja App at least  once a month. You agree that you will maintain your Ninja ID in confidence and not share  your Ninja ID with any third party. You will immediately notify Company of any actual or  suspected breach or improper use or disclosure of your Ninja ID or the Ninja App.

            2.2 Provision of Customer Services. When the Ninja App is active, User requests for  Customer Services may appear to you via the Ninja App if you are available and certified for work on the User’s account. If you accept a User’s request for Customer Services, the BITE NINJA Services  will provide you with certain User Information via the Ninja App, including the User’s name and point of access. In order to enhance User satisfaction with the BITE NINJA mobile application and  your Customer Services, it is recommended that you access the system at least ten (10) minutes early for a  shift for that User. You acknowledge and agree that once you have  accepted a User’s request for Customer Services, BITE NINJA’s mobile application may provide  certain information about you to the User, including your first name, contact information, photo  and location, and your Computer’s identifying information. You shall not contact any Users  or use any User’s personal data for any reason other than for the purposes of fulfilling  Customer Services. As between Company and you, you acknowledge and agree that:  (a)  you shall be solely responsible for determining the most effective, efficient and safe manner to  perform each instance of Customer Services; and (b) except for the BITE NINJA Services or any  Company Devices (if applicable), you shall provide all necessary equipment, tools and other  materials, at your own expense, necessary to perform Customer Services. You understand  and agree that you have a legal obligation under the Americans with Disabilities Act and similar  state laws to service Users with disabilities. Your knowing failure to service a User with  a disability shall constitute a material breach of this Agreement. You agree that a “knowing  failure” to comply with this legal obligation shall constitute either: (1) a denial of a service where  you state the denial was due to a disability; or (2) there is more than one (1) instance in  which a User or the manager of a User alleges that you cancelled or refused a service on the  basis of a disability.

            2.3 Your Relationship with Users. You acknowledge and agree that your provision of Customer  Services to Users creates a direct business relationship between you and the User. Company is  not responsible or liable for the actions or inactions of a User in relation to you, your activities or  your Computer. You shall have the sole responsibility for any obligations or liabilities to Users or  third parties that arise from your provision of Customer Services. You acknowledge and

            agree that you are solely responsible for taking such precautions as may be reasonable and  proper (including maintaining adequate insurance that meets the requirements of all applicable  laws including secure Computer financial responsibility laws) regarding any acts or omissions of a  User or third party. You acknowledge and agree that Company may release your contact and/or  access information to a User upon such User’s reasonable request. You acknowledge and  agree that, unless specifically consented to by a User, you may not Service or allow access to your  Computer individuals other than a User and any individuals authorized by such User, during the  performance of Customer Services for such User. You acknowledge and agree that all Users  should be Serviced directly to their specified destination, as directed by the applicable User,  without unauthorized interruption or unauthorized stops.

            2.4 Your Relationship with Company. You acknowledge and agree that Company’s provision to you  of the Ninja App and the BITE NINJA Services creates a direct business relationship between Company  and you. Company does not, and shall not be deemed to, direct or control you generally or in  your performance under this Agreement specifically, including in connection with your provision  of Customer Services, your acts or omissions, or your operation and maintenance of your  Computer. You retain the sole right to determine when, where, and for how long you will utilize  the Ninja App or the BITE NINJA Services. You retain the option, via the Ninja App, to attempt to  accept or to decline or ignore a User’s request for Customer Services via the BITE NINJA Services,  or to cancel an accepted request for Customer Services via the Ninja App, subject to  Company’s then-current cancellation policies. With the exception of any signage required by  local law or permit/license requirements, Company shall have no right to require you to:  (a)  display Company’s or any of its Affiliates’ names, logos or colors on your Computer(s); or (b) wear a  uniform or any other clothing displaying Company’s or any of its Affiliates’ names, logos or  colors. You acknowledge and agree that you have complete discretion to provide services or  otherwise engage in other business or employment activities.  For the sake of clarity, you  understand that you retain the complete right to; (i) use other software application services in  addition to the BITE NINJA Services; and (ii) engage in any other occupation or business. Company  retains the right to deactivate or otherwise restrict you from accessing or using the Ninja App  or the BITE NINJA Services in the event of a violation or alleged violation of this Agreement, your  disparagement of Company or any of its Affiliates, your act or omission that causes harm to  Company’s or its Affiliates’ brand, reputation or business as determined by Company in its sole  discretion.

            2.5 Ratings.

            2.5.1 You acknowledge and agree that:  (a) after receiving Customer Services, a User will  be prompted by BITE NINJA’s mobile application to provide a rating of you and such

            Customer Services and, optionally, to provide comments or feedback about you  and such Customer Services; and (b) after providing Customer Services, you  will be prompted by the Ninja App to provide a rating of the User and, optionally, to  provide comments or feedback about the User. You shall provide your ratings and  feedback in good faith.

            2.5.2 You acknowledge that Company desires that Users have access to high-quality services  via BITE NINJA’s mobile application. In order to continue to receive access to the Ninja App  and the BITE NINJA Services, you must maintain an average rating by Users that exceeds the  minimum average acceptable rating established by Company for your Account, as may  be updated from time to time by Company in its sole discretion (“Minimum Average  Rating”). Your average rating is intended to reflect Users’ satisfaction with your

            Customer Services rather than your compliance with any of Company’s policies or  recommendations. In the event your average rating falls below the Minimum Average  Rating, Company will notify you and may provide you, in Company’s discretion, a limited  period of time to raise your average rating above the Minimum Average Rating. If you  do not increase your average rating above the Minimum Average Rating within the time  period allowed (if any), Company reserves the right to deactivate your access to the  Ninja App and the BITE NINJA Services. Additionally, you acknowledge that your repeated  failure to accept User requests for Customer Services while you are logged in to the  Ninja App creates a negative experience for Users of BITE NINJA’s mobile application. If you  do not wish to accept User requests for Customer Services for a period of time, you  agree that you will log off of the Ninja App.

            2.5.3 Company and its Affiliates reserve the right to use, share and display your and User  ratings and comments in any manner in connection with the business of Company and  its Affiliates without attribution to you or your approval. You acknowledge and agree  that Company and its Affiliates are distributors (without any obligation to verify) and not  publishers of your and User ratings and comments, provided that Company and its  Affiliates reserve the right to edit or remove comments in the event that such

            comments include obscenities or other objectionable content, include an individual’s  name or other personal information, or violate any privacy laws, other applicable laws  or Company’s or its Affiliates’ content policies.

            2.6 Devices.

            2.6.1 Company encourages you to use Your Device in providing Customer Services.  Otherwise, if you elect to use any Company Devices, Company will supply you upon  request with Company Devices and provide the necessary wireless data plan for such  Devices, provided that Company will require reimbursement from you for the costs  associated with the wireless data plan of each Company Device and/or request a deposit  for each Company Device. You agree that:  (a) Company Devices may only be used for  the purpose of enabling your access to the BITE NINJA Services; and (b) Company Devices may  not be transferred, loaned, sold or otherwise provided in any manner to any party other  than you. Company Devices shall at all times remain the property of Company, and upon  termination of this Agreement or your termination or deactivation, you agree to return  to Company the applicable Company Devices within ten (10) days. You agree that failure  to timely return any Company Devices, or damage to Company Devices outside of  “normal wear and tear,” will result in the forfeiture of related deposits.

            2.6.2 If you elect to use Your Devices:  (i) you are responsible for the acquisition, cost and  maintenance of Your Devices as well as any necessary wireless data plan; and (ii)  Company shall make available the Ninja App for installation on Your Device. Company  hereby grants you a personal, non-exclusive, non-transferable license to install and use  the Ninja App on Your Device solely for the purpose of providing Customer  Services.  You agree to not provide, distribute or share, or enable the provision,  distribution or sharing of, the Ninja App (or any data associated therewith) with any  third party.  The foregoing license grant shall immediately terminate and you will delete  and fully remove the Ninja App from the Ninja-Provided Device in the event that you  cease to provide Customer Services using Your Device. You agree that:  (i) use of  the Ninja App on Your Device requires an active data plan with a wireless carrier  associated with Your Device, which data plan will be provided by you at your own

            expense; and (ii) use of the Ninja App on Your Device as an interface with the BITE NINJA  Services may consume very large amounts of data through the data plan.  COMPANY  ADVISES THAT YOUR DEVICE ONLY BE USED UNDER A DATA PLAN WITH UNLIMITED  OR VERY HIGH DATA USAGE LIMITS, AND COMPANY SHALL NOT BE RESPONSIBLE OR  LIABLE FOR ANY FEES, COSTS, OR OVERAGE CHARGES ASSOCIATED WITH ANY DATA  PLAN.

            2.7 Account Based Services. You acknowledge and agree that your network and hardware information must  be provided to the BITE NINJA Services via a Device in order to provide Customer Services. You  acknowledge and agree that:  (a) your network and hardware information may be obtained  by the BITE NINJA  Services while the Ninja App is running; and (b) the approximate location of your Computer will be  displayed to the User before and during the provision of Customer Services to such User. In  addition, Company and its Affiliates may monitor, track and share with third parties Ninja’s  network, hardware, and geo-location information obtained by the Ninja App and Device for safety and security  purposes.

            3. You and Your Computer

            3.1 Your Requirements. You acknowledge and agree that at all times, you shall:  (a) hold and  maintain (i) a high-functioning computer with the appropriate level of knowledge to operate your  Computer, and (ii) all authority applicable to you that are  necessary to provide Customer Service services to third parties in the Account; (b)  possess the appropriate and current level of training, expertise and experience to provide  Customer Services in a professional manner with due skill, care and diligence; and (c)  maintain high standards of professionalism, service and courtesy. You acknowledge and agree  that you may be subject to certain background and working record checks from time to time in  order to qualify to provide, and remain eligible to provide, Customer Services. You  acknowledge and agree that Company reserves the right, at any time in Company’s sole  discretion, to deactivate or otherwise restrict you from accessing or using the Ninja App or the  BITE NINJA Services if you fail to meet the requirements set forth in this Agreement.

            3.2 Computer Requirements. You acknowledge and agree that your Computer shall at all times be:  (a)  properly maintained and secured to operate as a Customer Service Computer in the  Account; (b) owned or leased by you, or otherwise in your lawful possession; (c) suitable for  performing the Customer Service services contemplated by this Agreement; and (d)  maintained in good operating condition, consistent with industry safety and maintenance  standards for a Computer of its kind and any additional standards or requirements in the applicable  Account, and in a clean and secure condition.

            3.3 Documentation. To ensure your compliance with all requirements in Sections 3.1 and 3.2 above,  you must provide Company with written copies of all such proof prior to your provision of any Customer Services.  Thereafter, you must submit to Company written evidence of all proof if they are renewed and as they are renewed. Company shall, upon  request, be entitled to review such proof and renewals from time to time, and your failure to provide or maintain any of the foregoing  shall constitute a material breach of this Agreement. Company reserves the right to  independently verify your documentation from time to time in any way Company deems  appropriate in its reasonable discretion.

            4. Financial Terms

            4.1 Fee Calculation and Your Payment. You are entitled to charge a Fee for each instance of  completed Customer Services provided to a User that are obtained via the BITE NINJA Services  (“Fee”), where such Fee is calculated based upon a base Fee amount plus demand or performance adjustments (as  determined by Company using account-based services enabled through the Device) and/or time  amounts, as detailed at www.BITENINJA.com/fees for the applicable Account (“Fee Calculation”).  You acknowledge and agree that the Fee provided under the Fee Calculation is the only  payment you will receive in connection with the provision of Customer Services, and that  neither the Fee nor the Fee Calculation includes any gratuity. You:  (i) appoint Company as your limited payment collection agent solely for the  purpose of accepting the Fee, from the User on your behalf via the payment processing  functionality facilitated by the BITE NINJA Services; and (ii) agree that payment made by User to  Company (or to an Affiliate of Company acting as an agent of Company) shall be considered the  same as payment made directly by User to you. In addition, the parties acknowledge and agree  that as between you and Company, the Fee is a recommended amount, and the primary  purpose of the pre-arranged Fee is to act as the default amount in the event you do not  negotiate a different amount. You shall always have the right to: (i) charge a Fee that is less  than the pre-arranged Fee; or (ii) negotiate, at your request, a Fee that is lower than the pre arranged Fee (each of (i) and (ii) herein, a “Negotiated Fee”). Company shall consider all such  requests from you in good faith. Company agrees to remit, or cause to be remitted, to you on at  least a weekly basis:  (a) the Fee less the applicable Service Fee; (b) depending  on the account, certain taxes and ancillary fees. If you have separately agreed that other amounts  may be deducted from the Fee prior to remittance to you (e.g., Computer financing payments,  lease payments, mobile device usage charges, etc.), the order of any such deductions from the  Fee shall be determined exclusively by Company (as between you and Company).

            4.2 Changes to Fee Calculation. Company reserves the right to change the Fee Calculation at any  time in Company’s discretion based upon local market factors, and Company will provide you  with notice in the event of changes to the base Fee, per hour, and/or per minute amounts that  would result in a change in the recommended Fee. Continued use of the BITE NINJA Services after  any such change in the Fee Calculation shall constitute your consent to such change.

            4.3 Fee Adjustment. Company reserves the right to:  (i) adjust the Fee for a particular instance of  Customer Services (e.g., you performed services poorly, you failed to properly end a  particular instance of Customer Services in the Ninja App, technical error in the BITE NINJA  Services, etc.); or (ii) cancel the Fee for a particular instance of Customer Services (e.g.,  User is charged for Customer Services that were not provided, in the event of a User  complaint, fraud, etc.). Company’s decision to reduce or cancel the Fee in any such manner  shall be exercised in a reasonable manner.

            4.4 Service Fee. In consideration of Company’s provision of the Ninja App and the BITE NINJA Services for  your use and benefit hereunder, the User agrees to pay Company a service fee on a per  Customer Services transaction basis calculated as a percentage of the Fee determined by  the Fee Calculation (regardless of any Negotiated Fee), as provided to the User via email or  otherwise made available electronically by Company from time to time for the applicable  Account (“Service Fee”). In the event regulations applicable to the User Account require taxes to be  calculated on the Fee, Company shall calculate the Service Fee based on the Fee net of such  taxes. Company reserves the right to change the Service Fee at any time in Company’s discretion

            based upon account and market factors, and Company will provide Users with notice in the event of such  change. Continued use of the BITE NINJA Services after any such change in the Service Fee calculation  shall constitute your consent to such change.

            4.5 Cancellation Charges. You acknowledge and agree that Users may elect to cancel requests for  Customer Services that have been accepted by you via the Ninja App at any time prior to  your access to the system. In the event that a User cancels an accepted request for Customer Services,  Company may charge the User a cancellation fee on your behalf. If charged, this cancellation fee  shall be deemed the Fee for the cancelled Customer Services for the purpose of  remittance to you hereunder (“Cancellation Fee”). The parties acknowledge and agree that as  between you and Company, this Cancellation Fee is a recommended amount, and the primary  purpose of such Cancellation Fee is to act as the default amount in the event you do not  negotiate a different amount. You shall always have the right to:  (i) charge a cancellation fee  that is less than the Cancellation Fee; or (ii) negotiate, at your request, a cancellation fee that is  lower than the Cancellation Fee (each of (i) and (ii) herein, a “Negotiated Cancellation Fee”). If  charged, the Cancellation Fee (regardless of any Negotiated Cancellation Fee) shall be deemed  the Fee for the cancelled Customer Services for the purpose of remittance to you  hereunder.

            4.6 Receipts. As part of the BITE NINJA Services, Company provides Users a  system for the delivery of  receipts to Users for Customer Services rendered. Upon your completion of Customer  Services for a User, Company prepares an applicable receipt and issues such receipt to the User  via email on your behalf. Receipts for your services are also provided to you via email or the online portal  available to you through the BITE NINJA Services. Receipts could include the breakdown of amounts charged  to the User for Customer Services and may include specific information about you,  including your name, contact information and photo, as well as a description of your performance.  Any corrections to a Ninja’s receipt for Customer Services must be submitted to Company in  writing within three (3) business days after the completion of such Customer Services.  Absent such a notice, Company shall not be liable for any mistakes in or corrections to the  receipt or for recalculation or disbursement of the Fee.

            4.7 No Additional Amounts. You acknowledge and agree that, for the mutual benefit of the parties,  through advertising and marketing, Company and its Affiliates may seek to attract new Users to  BITE NINJA and to increase existing Users’ use of BITE NINJA’s mobile application. You acknowledge and  agree such advertising or marketing does not entitle you to any additional monetary amounts  beyond the amounts expressly set forth in this Agreement.

            4.8 Taxes. You acknowledge and agree that you are required to:  (a) complete all tax registration  obligations and calculate and remit all tax liabilities related to your provision of Customer  Services as required by applicable law; and (b) provide Company with all relevant tax  information. You further acknowledge and agree that you are responsible for taxes on your own  income arising from the performance of Customer Services. Notwithstanding anything to  the contrary in this Agreement, Company may in its reasonable discretion based on applicable  tax and regulatory considerations, collect and remit taxes resulting from your provision of  Customer Services and/or provide any of the relevant tax information you have provided  pursuant to the foregoing requirements in this Section 4.8 directly to the applicable  governmental tax authorities on your behalf or otherwise.

            5. Proprietary Rights; License

            5.1 License Grant. Subject to the terms and conditions of this Agreement, Company hereby grants  you a non-exclusive, non-transferable, non-sublicensable, non-assignable license, during the  term of this Agreement, to use the BITE NINJA Services (including the Ninja App on a Device) solely  for the purpose of providing Customer Services to Users and tracking resulting Fees and  Fees. All rights not expressly granted to you are reserved by Company, its Affiliates and their  respective licensors.

            5.2 Restrictions. You shall not, and shall not allow any other party to:  (a) license, sublicense, sell,  resell, transfer, assign, distribute or otherwise provide or make available to any other party the  BITE NINJA Services, Ninja App or any Company Device in any way; (b) modify or make derivative  works based upon the BITE NINJA Services or Ninja App; (c) improperly use the BITE NINJA Services or  Ninja App, including creating Internet “links” to any part of the BITE NINJA Services or Ninja App,  “framing” or “mirroring” any part of the BITE NINJA Services or Ninja App on any other websites or  systems, or “scraping” or otherwise improperly obtaining data from the BITE NINJA Services or Ninja  App; (d) reverse engineer, decompile, modify, or disassemble the BITE NINJA Services or Ninja App,  except as allowed under applicable law; or (e) send spam or otherwise duplicative or unsolicited  messages. In addition, you shall not, and shall not allow any other party to, access or use the  BITE NINJA Services or Ninja App to:  (i) design or develop a competitive or substantially similar  product or service; (ii) copy or extract any features, functionality, or content thereof; (iii) launch  or cause to be launched on or in connection with the BITE NINJA Services an automated program or  script, including web spiders, crawlers, robots, indexers, bots, viruses or worms, or any program  which may make multiple server requests per second, or unduly burden or hinder the operation  and/or performance of the BITE NINJA Services; or (iv) attempt to gain unauthorized access to the  BITE NINJA Services or its related systems or networks.

            5.3 Ownership. The BITE NINJA Services, Ninja App and Company Data, including all intellectual property  rights therein, and the Company Devices are and shall remain (as between you and Company)  the property of Company, its Affiliates or their respective licensors. Neither this Agreement nor  your use of the BITE NINJA Services, Ninja App or Company Data conveys or grants to you any rights  in or related to the BITE NINJA Services, Ninja App or Company Data, except for the limited license  granted above. Other than as specifically permitted by the Company in connection with the  BITE NINJA Services, you are not permitted to use or reference in any manner Company’s, its  Affiliates’, or their respective licensors’ company names, logos, products and service names,  trademarks, service marks, trade dress, copyrights or other indicia of ownership, alone and in  combination with other letters, punctuation, words, symbols and/or designs (the "BITE NINJA Marks  and Names") for any commercial purposes. You agree that you will not try to register or  otherwise use and/or claim ownership in any of the BITE NINJA Marks and Names, alone or in  combination with other letters, punctuation, words, symbols and/or designs, or in any  confusingly similar mark, name or title, for any goods and services.

            6. Confidentiality

            6.1 Each party acknowledges and agrees that in the performance of this Agreement it may have  access to or may be exposed to, directly or indirectly, confidential information of the other party  ("Confidential Information"). Confidential Information includes Company Data, Ninja IDs, User  Information, and the transaction volume, marketing and business plans, business, financial,  technical, operational and such other non-public information of each party (whether disclosed  in writing or verbally) that such party designates as being proprietary or confidential or of which  the other party should reasonably know that it should be treated as confidential.

            6.2 Each party acknowledges and agrees that:  (a) all Confidential Information shall remain the  exclusive property of the disclosing party; (b) it shall not use Confidential Information of the  other party for any purpose except in furtherance of this Agreement; (c) it shall not disclose  Confidential Information of the other party to any third party, except to its employees, officers,  contractors, agents and service providers ("Permitted Persons") as necessary to perform under  this Agreement, provided Permitted Persons are bound in writing to obligations of  confidentiality and non-use of Confidential Information no less protective than the terms  hereof; and (d) it shall return or destroy all Confidential Information of the disclosing party,  upon the termination of this Agreement or at the request of the other party (subject to  applicable law and, with respect to Company, its internal record-keeping requirements).

            6.3 Notwithstanding the foregoing, Confidential Information shall not include any information to  the extent it:  (a) is or becomes part of the public domain through no act or omission on the part  of the receiving party; (b) was possessed by the receiving party prior to the date of this  Agreement without an obligation of confidentiality; (c) is disclosed to the receiving party by a  third party having no obligation of confidentiality with respect thereto; or (d) is required to be  disclosed pursuant to law, court order, subpoena or governmental authority, provided the  receiving party notifies the disclosing party thereof and provides the disclosing party a  reasonable opportunity to contest or limit such required disclosure.

            7. Privacy

            7.1 Disclosure of Your Information. Subject to applicable law, Company and its Affiliates may, but  shall not be required to, provide to you, a User, an insurance company and/or relevant  authorities and/or regulatory agencies any information (including personal information (e.g.,  information obtained about you through any background check) and any Company Data) about  you or any Customer Services provided hereunder if:  (a) there is a complaint, dispute or  conflict, including an accident, between you and a User; (b) it is necessary to enforce the terms  of this Agreement; (c) it is required, in Company’s or any Affiliate’s sole discretion, by applicable  law or regulatory requirements (e.g., Company or its Affiliates receive a subpoena, warrant, or  other legal process for information); (d) it is necessary, in Company’s or any Affiliate’s sole  discretion, to (1) protect the safety, rights, property or security of Company or its Affiliates, the  BITE NINJA Services or any third party; (2) to protect the safety of the public for any reason including  the facilitation of insurance claims related to the BITE NINJA Services;  (3) to detect, prevent or  otherwise address fraud, security or technical issues;  (4) to prevent or stop activity which  Company or any of its Affiliates, in their sole discretion, may consider to be, or to pose a risk of  being, an illegal, unethical, or legally actionable activity); or (e) it is required or necessary, in  Company’s or any Affiliate’s sole discretion, for insurance or other purposes related to your  ability to qualify, or remain qualified, to use the BITE NINJA Services. You understand that Company  may retain your personal data for legal, regulatory, safety and other necessary purposes after  this Agreement is terminated.

            7.2 Company and its Affiliates may collect your personal data during the course of your application  for, and use of, the BITE NINJA Services, or may obtain information about you from third parties. Such  information may be stored, processed, transferred, and accessed by Company and its Affiliates,  third parties, and service providers for business purposes, including for marketing, lead  generation, service development and improvement, analytics, industry and market research,  and such other purposes consistent with Company’s and its Affiliates’ legitimate business needs.  You expressly consent to such use of personal data.

            8. Insurance

            8.1 Company maintains adequate insurance during the course of doing business under this agreement.

            8.2 You agree to maintain during the term of this Agreement workers’ compensation insurance as  required by all applicable laws in the Account. If permitted by applicable law, you may choose  to insure yourself against industrial injuries by maintaining occupational accident insurance in  place of workers’ compensation insurance. Furthermore, if permitted by applicable law, you  may choose not to insure yourself against industrial injuries at all, but do so at your own risk.

            8.3 You understand and acknowledge that your personal insurance may not cover all activities that occur during the course of doing business. If you have any questions or concerns about the scope  or applicability of your own insurance coverage, it is your responsibility, not that of Company, to  resolve them with your insurer(s).

            8.4 Company may maintain during the term of this Agreement insurance related to your provision  of Customer Services as determined by Company in its reasonable discretion or as  described in a City Addendum, provided that Company and its Affiliates are not required to  provide you with any specific insurance coverage for any loss to you or your Computer. You are  required to promptly notify Company of any computer damage that occurs while providing Customer  Services and to cooperate and provide all necessary information related thereto.

            9. Representations and Warranties; Disclaimers

            9.1 By You. You hereby represent and warrant that:  (a) you have full power and authority to enter  into this Agreement and perform your obligations hereunder; (b) you have not entered into, and  during the term will not enter into, any agreement that would prevent you from complying with  this Agreement; and (c) you will comply with all applicable laws in your performance of this  Agreement, including holding and complying with all permits, licenses, registrations and other  governmental authorizations necessary to provide (i) Customer Services using the Computers  pursuant to this Agreement, and (ii) Customer Service services to third parties in the  Account generally.

            9.2 Disclaimer of Warranties. COMPANY AND ITS AFFILIATES PROVIDE, AND YOU ACCEPT, THE BITE NINJA SERVICES, Ninja APP AND THE COMPANY DEVICES ON AN "AS IS" AND "AS AVAILABLE" BASIS. COMPANY AND ITS AFFILIATES DO NOT REPRESENT, WARRANT OR GUARANTEE THAT YOUR ACCESS TO OR USE OF THE BITE NINJA SERVICES, Ninja APP OR THE COMPANY DEVICES:  (A) WILL BE UNINTERRUPTED OR ERROR FREE; OR (B) WILL RESULT IN ANY REQUESTS FOR Customer

            SERVICES. COMPANY AND ITS AFFILIATES FUNCTION AS AN ON-DEMAND LEAD GENERATION AND RELATED SERVICE ONLY AND MAKE NO REPRESENTATIONS, WARRANTIES OR GUARANTEES AS TO THE ACTIONS OR INACTIONS OF THE USERS WHO MAY REQUEST OR RECEIVE Customer SERVICES FROM YOU, AND COMPANY AND ITS AFFILIATES DO NOT SCREEN OR OTHERWISE EVALUATE USERS. BY USING THE BITE NINJA SERVICES AND Ninja APP, YOU ACKNOWLEDGE AND AGREE THAT YOU MAY BE INTRODUCED TO A THIRD PARTY THAT MAY POSE HARM OR RISK TO YOU OR OTHER THIRD PARTIES. YOU ARE ADVISED TO TAKE REASONABLE PRECAUTIONS WITH RESPECT TO INTERACTIONS WITH THIRD PARTIES ENCOUNTERED IN CONNECTION WITH THE USE OF THE BITE NINJA SERVICES OR Ninja APP.NOTWITHSTANDING COMPANY’S APPOINTMENT AS THE LIMITED PAYMENT COLLECTION AGENT OF YOU FOR THE PURPOSE OF ACCEPTING PAYMENT FROM USERS ON YOUR BEHALF AS SET FORTH IN SECTION 4 ABOVE, COMPANY AND ITS AFFILIATES EXPRESSLY DISCLAIM ALL LIABILITY FOR ANY ACT OR OMISSION OF YOU, ANY USER OR OTHER THIRD PARTY.

            9.3 No Service Guarantee. COMPANY AND ITS AFFILIATES DO NOT GUARANTEE THE AVAILABILITY OR UPTIME OF THE BITE NINJA SERVICES OR Ninja APP. YOU ACKNOWLEDGE AND AGREE THAT THE BITE NINJA SERVICES OR Ninja APP MAY BE UNAVAILABLE AT ANY TIME AND FOR ANY REASON (e.g., DUE TO SCHEDULED MAINTENANCE OR NETWORK FAILURE). FURTHER, THE BITE NINJA SERVICES OR  Ninja APP MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN  THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS, AND COMPANY AND ITS  AFFILIATES ARE NOT RESPONSIBLE FOR ANY DELAYS, ACCESS FAILURES, OR OTHER DAMAGES,  LIABILITIES OR LOSSES RESULTING FROM SUCH PROBLEMS.

            10. Indemnification. You shall indemnify, defend (at Company’s option) and hold harmless Company  and its Affiliates and their respective officers, directors, employees, agents, successors and assigns  from and against any and all liabilities, expenses (including legal fees), damages, penalties, fines,  social security contributions and taxes arising out of or related to:  (a) your breach of your  representations, warranties or obligations under this Agreement; or (b) a claim by a third party  (including Users, regulators and governmental authorities) directly or indirectly related to your  provision of Customer Services or use of the BITE NINJA Services. This indemnification provision shall  not apply to your breach of any representations regarding your status as an independent contractor.

            11. Limits of Liability.  COMPANY AND ITS AFFILIATES SHALL NOT BE LIABLE UNDER OR RELATED TO  THIS AGREEMENT FOR ANY OF THE FOLLOWING, WHETHER BASED ON CONTRACT, TORT OR ANY  OTHER LEGAL THEORY, EVEN IF A PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH  DAMAGES:  (i) ANY INCIDENTAL, PUNITIVE, SPECIAL, EXEMPLARY, CONSEQUENTIAL, OR OTHER  INDIRECT DAMAGES OF ANY TYPE OR KIND; OR (ii) YOUR OR ANY THIRD PARTY’S PROPERTY  DAMAGE, OR LOSS OR INACCURACY OF DATA, OR LOSS OF BUSINESS, REVENUE, PROFITS, USE OR  OTHER ECONOMIC ADVANTAGE. EXCEPT FOR COMPANY’S OBLIGATIONS TO PAY AMOUNTS DUE TO  YOU PURSUANT TO SECTION 4 ABOVE, BUT SUBJECT TO ANY LIMITATIONS OR OTHER PROVISIONS  CONTAINED IN THIS AGREEMENT WHICH ARE APPLICABLE THERETO, IN NO EVENT SHALL THE  LIABILITY OF COMPANY OR ITS AFFILIATES UNDER THIS AGREEMENT EXCEED THE AMOUNT OF  SERVICE FEES ACTUALLY PAID TO OR DUE TO COMPANY HEREUNDER IN THE SIX (6) MONTH PERIOD  IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM.

            12. Term and Termination

            12.1 Term.  This Agreement shall commence on the date accepted by you and shall continue until  terminated as set forth herein.

            12.2 Termination. Either party may terminate this Agreement:  (a) without cause at any time upon  seven (7) days prior written notice to the other party; (b) immediately, without notice, for the  other party’s material breach of this Agreement; or (c) immediately, without notice, in the event  of the insolvency or bankruptcy of the other party, or upon the other party’s filing or submission  of request for suspension of payment (or similar action or event) against the terminating party.  In addition, Company may terminate this Agreement or deactivate your Ninja ID immediately,  without notice, with respect to you in the event you no longer qualify, under applicable law or  the standards and policies of Company and its Affiliates, to provide Customer Services or to  operate the Computer, or as otherwise set forth in this Agreement.

            12.3 Effect of Termination. Upon termination of the Agreement, you shall:  (a) promptly return to Company all Company Devices; and (b) immediately delete and fully remove the Ninja App  from any of Your Devices. Outstanding payment obligations and Sections 1, 2.3, 2.5.3, 4.7, 4.8,  5.3, 6, 7, 9, 10, 11, 12.3, 13, 14 and 15 shall survive the termination of this Agreement.

            13. Relationship of the Parties

            13.1 Except as otherwise expressly provided herein with respect to Company acting as the limited  payment collection agent solely for the purpose of collecting payment from Users on your  behalf, the relationship between the parties under this Agreement is solely that of  independent contracting parties. The parties expressly agree that:  (a) this Agreement is not  an employment agreement, nor does it create an employment relationship, between  Company and you; and (b) no joint venture, partnership, or agency relationship exists  between Company and you.

            13.2 You have no authority to bind Company or its Affiliates and you undertake not to hold yourself  out as an employee, agent or authorized representative of Company or its Affiliates. Where, by  implication of mandatory law or otherwise, you may be deemed an agent or representative of  Company, you undertake and agree to indemnify, defend (at Company’s option) and hold  Company and its Affiliates harmless from and against any claims by any person or entity based  on such implied agency or representative relationship.

            14. Miscellaneous Terms

            14.1 Modification.  In the event Company modifies the terms and conditions of this Agreement at  any time, such modifications shall be binding on you only upon your acceptance of the modified  Agreement. Company reserves the right to modify any information referenced at hyperlinks  from this Agreement from time to time. You hereby acknowledge and agree that, by using the  BITE NINJA Services, or downloading, installing or using the Ninja App, you are bound by any future  amendments and additions to information referenced at hyperlinks herein, or documents  incorporated herein, including with respect to Fee Calculations. Continued use of the BITE NINJA  Services or Ninja App after any such changes shall constitute your consent to such changes.  Unless changes are made to the arbitration provisions herein, you acknowledge and agree that  modification of this Agreement does not create a renewed opportunity to opt out of arbitration.

            14.2 Supplemental Terms. Supplemental terms may apply to your use of the BITE NINJA Services, such as  use policies or terms related to certain features and functionality, which may be modified from  time to time (“Supplemental Terms”). You may be presented with certain Supplemental Terms  from time to time. Supplemental Terms are in addition to, and shall be deemed a part of, this  Agreement. Supplemental Terms shall prevail over this Agreement in the event of a conflict.

            14.3 Severability. If any provision of this Agreement is or becomes invalid or non-binding, the parties  shall remain bound by all other provisions hereof. In that event, the parties shall replace the  invalid or non-binding provision with provisions that are valid and binding and that have, to the  greatest extent possible, a similar effect as the invalid or non-binding provision, given the  contents and purpose of this Agreement.

            14.4 Assignment. Neither party shall assign or transfer this Agreement or any of its rights or  obligations hereunder, in whole or in part, without the prior written consent of the other party;  provided that Company may assign or transfer this Agreement or any or all of its rights or  obligations under this Agreement from time to time without consent:  (a) to an Affiliate; or (b)  to an acquirer of all or substantially all of Company’s business, equity or assets.

            14.5 Entire Agreement. This Agreement, including all Supplemental Terms, constitutes the entire  agreement and understanding of the parties with respect to its subject matter and replaces and  supersedes all prior or contemporaneous agreements or undertakings regarding such subject  matter. In this Agreement, the words “including” and “include” mean “including, but not limited  to.” The recitals form a part of this Agreement.

            14.6 No Third Party Beneficiaries. There are no third party beneficiaries to this Agreement, except as  expressly set forth in the Arbitration Provision in Section 15.3. Nothing contained in this  Agreement is intended to or shall be interpreted to create any third-party beneficiary claims.

            14.7 Notices.  Any notice delivered by Company to you under this Agreement will be delivered by  email to the email address associated with your account or by posting on the portal available to  you on the BITE NINJA Services. Any notice delivered by you to Company under this Agreement will be  delivered by contacting Company at INFO@BITENINJA.COM .  Additional Account-specific notices may be required from time to time.

            15. Governing Law; Arbitration

            15.1 The choice of law provisions contained in this Section 15.1 do not apply to the arbitration clause  contained in Section 15.3, such arbitration clause being governed by the Federal Arbitration Act.  Accordingly, and except as otherwise stated in Section 15.3, the interpretation of this  Agreement shall be governed by TENNESSEE law, without regard to the choice or conflicts of law  provisions of any jurisdiction.  Any disputes, actions, claims or causes of action arising out of or  in connection with this Agreement or the BITE NINJA Services that are not subject to the arbitration  clause contained in Section 15.3 shall be subject to the exclusive jurisdiction of the state and  federal courts located in the county of Shelby and city of Memphis, TENNESSEE. However, neither the  choice of law provision regarding the interpretation of this Agreement nor the forum selection  provision is intended to create any other substantive right to non-TENNESSEEns to assert claims  under TENNESSEE law whether that be by statute, common law, or otherwise. These provisions,  and except as otherwise provided in Section 15.3, are only intended to specify the use of  TENNESSEE law to interpret this Agreement and the forum for disputes asserting a breach of this  Agreement, and these provisions shall not be interpreted as generally extending TENNESSEE law  to you if you do not otherwise reside or provide services in TENNESSEE. The foregoing choice of  law and forum selection provisions do not apply to the arbitration clause in Section 15.3 or to  any arbitrable disputes as defined therein. Instead, as described in Section 15.3, the Federal  Arbitration Act shall apply to any such disputes.  The failure of Company to enforce any right or  provision in this Agreement shall not constitute a waiver of such right or provision unless

            acknowledged and agreed to by BITE NINJA in writing.

            15.2 Other than disputes regarding the intellectual property rights of the parties and other claims  identified in Section 15.3.ii, any disputes, actions, claims or causes of action arising out of or in  connection with this Agreement or the BITE NINJA Services shall be subject to arbitration pursuant to  Section 15.3.

            15.3 Arbitration Provision

            Important Note Regarding this Arbitration Provision:

            ● Except as provided below, arbitration does not limit or affect the legal claims you may  bring against the Company.  Agreeing to arbitration only affects where any such claims  may be brought and how they will be resolved.

            ● Arbitration is a process of private dispute resolution that does not involve the civil  courts, a civil judge, or a jury.  Instead, the parties’ dispute is decided by a private  arbitrator selected by the parties using the process set forth herein.  Other arbitration  rules and procedures are also set forth herein.

            ● Unless the law requires otherwise, as determined by the Arbitrator based upon the  circumstances presented, you will be required to split the cost of any arbitration with  the Company.

            ● IMPORTANT: This Arbitration Provision will require you to resolve  any claim that you may have against the Company or BITE NINJA on an  individual basis, except as provided below, pursuant to the terms of  the Agreement unless you choose to opt out of the Arbitration  Provision.  Except as provided below, this provision will preclude you  from bringing any class, collective, or representative action (other  than actions under the Private Attorneys General Act of 2004  (“PAGA”), TENNESSEE Labor Code § 2698 et seq. (“PAGA”)) against the  Company or BITE NINJA, and also precludes you from participating in or  recovering relief under any current or future class, collective, or  representative (non-PAGA) action brought against the Company or  BITE NINJA by someone else.


            

            WHETHER TO AGREE TO ARBITRATION IS AN IMPORTANT BUSINESS DECISION.   IT IS YOUR DECISION TO MAKE, AND YOU SHOULD NOT RELY SOLELY UPON THE  INFORMATION PROVIDED IN THIS AGREEMENT AS IT IS NOT INTENDED TO  CONTAIN A COMPLETE EXPLANATION OF THE CONSEQUENCES OF  ARBITRATION.  YOU SHOULD TAKE REASONABLE STEPS TO CONDUCT FURTHER

            RESEARCH AND TO CONSULT WITH OTHERS — INCLUDING BUT NOT LIMITED TO  AN ATTORNEY — REGARDING THE CONSEQUENCES OF YOUR DECISION, JUST AS  YOU WOULD WHEN MAKING ANY OTHER IMPORTANT BUSINESS OR LIFE  DECISION.

            i. How This Arbitration Provision Applies.

            This Arbitration Provision is governed by the Federal Arbitration Act, 9 U.S.C. § 1 et seq. (the “FAA”) and  evidences a transaction involving interstate commerce.  This Arbitration Provision applies to any dispute  arising out of or related to this Agreement or termination of the Agreement and survives after the  Agreement terminates.  Nothing contained in this Arbitration Provision shall be construed to prevent or  excuse you from utilizing any informal procedure for resolution of complaints established in this  Agreement (if any), and this Arbitration Provision is not intended to be a substitute for the utilization of  such procedures.

            Except as it otherwise provides, this Arbitration Provision is intended to apply to the resolution of  disputes that otherwise would be resolved in a court of law or before any forum other than  arbitration, with the exception of proceedings that must be exhausted under applicable law before  pursuing a claim in a court of law or in any forum other than arbitration.  Except as it otherwise  provides, this Arbitration Provision requires all such disputes to be resolved only by an arbitrator  through final and binding arbitration on an individual basis only and not by way of court or jury trial,  or by way of class, collective, or representative action.

            Except as provided in Section 15.3(v), below, regarding the Class Action Waiver, such disputes include  without limitation disputes arising out of or relating to interpretation or application of this Arbitration  Provision, including the enforceability, revocability or validity of the Arbitration Provision or any portion  of the Arbitration Provision.  All such matters shall be decided by an Arbitrator and not by a court or  judge. However, as set forth below, the preceding sentences shall not apply to disputes relating to the  interpretation or application of the Class Action Waiver or PAGA Waiver below, including their  enforceability, revocability or validity.

            Except as it otherwise provides, this Arbitration Provision also applies, without limitation, to all disputes  between You and the Company or BITE NINJA, as well as all disputes between You and the Company’s or  BITE NINJA’s fiduciaries, administrators, affiliates, subsidiaries, parents, and all successors and assigns of any  of them, including but not limited to any disputes arising out of or related to this Agreement and  disputes arising out of or related to your relationship with the Company, including termination of the  relationship.  This Arbitration Provision also applies, without limitation, to disputes regarding any city,  county, state or federal wage-hour law, trade secrets, unfair competition, compensation, breaks and  rest periods, expense reimbursement, termination, harassment and claims arising under the Uniform  Trade Secrets Act, Civil Rights Act of 1964, Americans With Disabilities Act, Age Discrimination in  Employment Act, Family Medical Leave Act, Fair Labor Standards Act, Employee Retirement Income  Security Act (except for individual claims for employee benefits under any benefit plan sponsored by the  Company and covered by the Employee Retirement Income Security Act of 1974 or funded by  insurance), Genetic Information Non-Discrimination Act, and state statutes, if any, addressing the same  or similar subject matters, and all other similar federal and state statutory and common law claims.

            This Agreement is intended to require arbitration of every claim or dispute that lawfully can be  arbitrated, except for those claims and disputes which by the terms of this Agreement are expressly  excluded from the Arbitration Provision.

            BITE NINJA, Inc. is an intended, third party beneficiary of this Agreement. ii. Limitations On How This Agreement Applies.

            The disputes and claims set forth below shall not be subject to arbitration and the requirement to  arbitrate set forth in this Arbitration Provision shall not apply:

            Claims for workers compensation, state disability insurance and unemployment insurance benefits;

            Regardless of any other terms of this Agreement, nothing prevents you from making a report to or filing  a claim or charge with the Equal Employment Opportunity Commission, U.S. Department of Labor,  Securities Exchange Commission, National Labor Relations Board, or Office of Federal Contract  Compliance Programs, and nothing in this Agreement or Arbitration Provision prevents the investigation  by a government agency of any report, claim or charge otherwise covered by this Arbitration Provision. Nothing in this Arbitration Provision shall be deemed to preclude or excuse a party from bringing an  administrative claim before any agency in order to fulfill the party's obligation to exhaust administrative  remedies before making a claim in arbitration;

            Disputes that may not be subject to a predispute arbitration agreement pursuant to applicable Federal  law or Executive Order are excluded from the coverage of this Arbitration Provision;

            Disputes regarding your, the Company’s, or BITE NINJA’s intellectual property rights;

            This Arbitration Provision shall not be construed to require the arbitration of any claims against a  contractor that may not be the subject of a mandatory arbitration agreement as provided by section  8116 of the Department of Defense ("DoD") Appropriations Act for Fiscal Year 2010 (Pub. L. 111-118),  section 8102 of the Department of Defense ("DoD") Appropriations Act for Fiscal Year 2011 (Pub. L. 112- 10, Division A), and their implementing regulations, or any successor DoD appropriations act addressing  the arbitrability of claims.

            iii. Selecting The Arbitrator and Location of the Arbitration.

            The Arbitrator shall be selected by mutual agreement of the Company and you.  Unless you and the  Company mutually agree otherwise, the Arbitrator shall be an attorney licensed to practice in the  location where the arbitration proceeding will be conducted or a retired federal or state judicial officer  who presided in the jurisdiction where the arbitration will be conducted.  If the Parties cannot agree on  an Arbitrator, then an arbitrator will be selected using the alternate strike method from a list of five (5)  neutral arbitrators provided by JAMS (Judicial Arbitration & Mediation Services).  You will have the  option of making the first strike.  If a JAMS arbitrator is used, then the JAMS Streamlined Arbitration Rules & Procedures rules will apply; however, if there is a conflict between the JAMS Rules and this  Agreement, this Agreement shall govern. Those rules are available here:

            http://www.jamsadr.com/rules-streamlined-arbitration/

            The location of the arbitration proceeding shall be no more than 45 miles from the place where you last  provided Customer services under this Agreement, unless each party to the arbitration agrees in  writing otherwise.

            iv. Starting The Arbitration.

            All claims in arbitration are subject to the same statutes of limitation that would apply in court.  The  party bringing the claim must demand arbitration in writing and deliver the written demand by hand or  first class mail to the other party within the applicable statute of limitations period.  The demand for  arbitration shall include identification of the Parties, a statement of the legal and factual basis of the  claim(s), and a specification of the remedy sought. Any demand for arbitration made to the Company or  BITE NINJA shall be provided to Legal, Cooley LLP, San Jose, CA.  The  arbitrator shall resolve all disputes regarding the timeliness or propriety of the demand for arbitration.   A party may apply to a court of competent jurisdiction for temporary or preliminary injunctive relief in  connection with an arbitrable controversy, but only upon the ground that the award to which that party  may be entitled may be rendered ineffectual without such provisional relief.

            v. How Arbitration Proceedings Are Conducted.

            In arbitration, the Parties will have the right to conduct adequate civil discovery, bring dispositive  motions, and present witnesses and evidence as needed to present their cases and defenses, and any  disputes in this regard shall be resolved by the Arbitrator.

            You and the Company agree to resolve any dispute that is in arbitration on an individual basis only,  and not on a class, collective action, or representative basis (“Class Action Waiver”). The Arbitrator  shall have no authority to consider or resolve any claim or issue any relief on any basis other than an  individual basis. The Arbitrator shall have no authority to consider or resolve any claim or issue any  relief on a class, collective, or representative basis.  Notwithstanding any other provision of this  Agreement, the Arbitration Provision or the JAMS Streamlined Arbitration Rules & Procedures, disputes  regarding the enforceability, revocability or validity of the Class Action Waiver may be resolved only by a  civil court of competent jurisdiction and not by an arbitrator. In any case in which (1) the dispute is filed  as a class, collective, or representative  action and (2) there is a final judicial determination that all or  part of the Class Action Waiver unenforceable, the class, collective, and/or representative action to that  extent must be litigated in a civil court of competent jurisdiction, but the portion of the Class Action  Waiver that is enforceable shall be enforced in arbitration.

            While the Company will not take any retaliatory action in response to any exercise of rights you may  have under Section 7 of the National Labor Relations Act, if any, the Company shall not be precluded  from moving to enforce its rights under the FAA to compel arbitration on the terms and conditions set  forth in this Agreement.

            Private Attorneys General Act.

            Notwithstanding any other provision of this Agreement or the Arbitration Provision, to the extent  permitted by law, (1) You and Company agree not to bring a representative action on behalf of others , in any  court or in arbitration, and (2) for any claim brought on a private attorney general basis—i.e., where

            you are seeking to pursue a claim on behalf of a government entity—both you and Company agree that  any such dispute shall be resolved in arbitration on an individual basis only (i.e., to resolve whether you  have personally been aggrieved or subject to any violations of law), and that such an action may not be  used to resolve the claims or rights of other individuals in a single or collective proceeding (i.e., to

            resolve whether other individuals have been aggrieved or subject to any violations of law) (“PAGA  Waiver”). Notwithstanding any other provision of this Agreement or the Arbitration Provision, the  validity of the PAGA Waiver may be resolved only by a civil court of competent jurisdiction and not by an  arbitrator. If any provision of the PAGA Waiver is found to be unenforceable or unlawful for any reason,  (1) the unenforceable provision shall be severed from this Agreement; (2) severance of the  unenforceable provision shall have no impact whatsoever on the Arbitration Provision or the Parties’  attempt to arbitrate any remaining claims on an individual basis pursuant to the Arbitration Provision;  and (3) any representative action brought under PAGA on behalf of others must be litigated in a civil  court of competent jurisdiction and not in arbitration. To the extent that there are any claims to be  litigated in a civil court of competent jurisdiction because a civil court of competent jurisdiction  determines that the PAGA Waiver is unenforceable with respect to those claims, the Parties agree that  litigation of those claims shall be stayed pending the outcome of any individual claims in arbitration.

            vi. Paying For The Arbitration.

            Each party will pay the fees for his, her or its own attorneys, subject to any remedies to which that party  may later be entitled under applicable law (i.e., a party prevails on a claim that provides for the award of  reasonable attorney fees to the prevailing party).  In all cases where required by law, the Company will  pay the Arbitrator's and arbitration fees. If under applicable law the Company is not required to pay all  of the Arbitrator’s and/or arbitration fees, such fee(s) will be apportioned equally between the Parties  or as otherwise required by applicable law. However, you will not be required to bear any type of fee or  expense that you would not be required to bear if you had filed the action in a court of law.  Any  disputes in that regard will be resolved by the Arbitrator as soon as practicable after the Arbitrator is  selected, and Company shall bear all of the Arbitrator’s and arbitration fees until such time as the  Arbitrator resolves any such dispute.

            vii. The Arbitration Hearing And Award.

            The Parties will arbitrate their dispute before the Arbitrator, who shall confer with the Parties regarding  the conduct of the hearing and resolve any disputes the Parties may have in that regard.  Within 30 days  of the close of the arbitration hearing, or within a longer period of time as agreed to by the Parties or as  ordered by the Arbitrator, any party will have the right to prepare, serve on the other party and file with

            the Arbitrator a brief.  The Arbitrator may award any party any remedy to which that party is entitled  under applicable law, but such remedies shall be limited to those that would be available to a party in  his or her individual capacity in a court of law for the claims presented to and decided by the Arbitrator,  and no remedies that otherwise would be available to an individual in a court of law will be forfeited by  virtue of this Arbitration Provision.  The Arbitrator will issue a decision or award in writing, stating the  essential findings of fact and conclusions of law.  A court of competent jurisdiction shall have the  authority to enter a judgment upon the award made pursuant to the arbitration.  The Arbitrator shall  not have the power to commit errors of law or legal reasoning, and the award may be vacated or  corrected on appeal to a court of competent jurisdiction for any such error.

            viii. Your Right To Opt Out Of Arbitration.

            Arbitration is not a mandatory condition of your contractual relationship with the Company.  If you do  not want to be subject to this Arbitration Provision, you may opt out of this Arbitration Provision by  notifying the Company in writing of your desire to opt out of this Arbitration Provision, either by (1)  sending, within 30 days of the date this Agreement is executed by you, electronic mail to  optout@BITE NINJA.com, stating your name and intent to opt out of the Arbitration Provision or (2) by  sending a letter by U.S. Mail, or by any nationally recognized delivery service (e.g, UPS, Federal  Express, etc.), or by hand delivery to:

            Legal

            Cooley LLP

            3175 Hanover St

            San Jose, CA 94304

            In order to be effective, the letter under option (2) must clearly indicate your intent to opt out of this  Arbitration Provision, and must be dated and signed. The envelope containing the signed letter must  be received (if delivered by hand) or post-marked within 30 days of the date this Agreement is  executed by you.  Your writing opting out of this Arbitration Provision, whether sent by (1) or (2), will  be filed with a copy of this Agreement and maintained by the Company.  Should you not opt out of  this Arbitration Provision within the 30-day period, you and the Company shall be bound by the terms  of this Arbitration Provision.  You have the right to consult with counsel of your choice concerning this  Arbitration Provision.  You understand that you will not be subject to retaliation if you exercise your  right to assert claims or opt-out of coverage under this Arbitration Provision.

            ix. Full and Complete Agreement Related to Formal Resolution of Disputes; Enforcement Of  This Agreement.

            This Arbitration Provision is the full and complete agreement relating to the formal resolution of  disputes arising out of this Agreement.  Except as stated in subsection v, above, in the event any portion  of this Arbitration Provision is deemed unenforceable, the remainder of this Arbitration Provision will be  enforceable.

            By clicking “I accept”, you expressly acknowledge that you have read, understood, and taken steps to  thoughtfully consider the consequences of this Agreement, that you agree to be bound by the terms and  conditions of the Agreement, and that you are legally competent to enter into this Agreement with  Company.
        </p>
    )
};

export default Terms;